on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing Printing'
        run: echo Abdo

